GET http://localhost:3000/todos/?status=TO%20DO

### 1
GET http://localhost:3000/todos/2

### 2

GET http://localhost:3000/agenda/?date=2021-1-21

###  3

GET http://localhost:3000/agenda/?date=:2021-1-21

### 3-1

POST http://localhost:3000/todos/
Content-Type: application/json

{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-09-22"
}


### 4

PUT http://localhost:3000/todos/1/
Content-Type: application/json

{
"todo": "Clean the garden"
}

### 5

DELETE http://localhost:3000/todos/4/

### 1-2

GET http://localhost:3000/todos/?category=WORK&status=DONE

### 1-3
GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH

### 1-4
GET http://localhost:3000/todos/?category=HOME

### 1-5

GET http://localhost:3000/todos/?priority=feewf

### 1-6
GET http://localhost:3000/todos/?category=dsf


###

PUT http://localhost:3000/todos/1/
Content-Type: application/json

{ "category": "LEARNING" }